name: redstone_utilities
version: 0.0.1
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: Utility classes and functions to speed development
homepage: https://github.com/redstone-dart/redstone_utilities
dependencies:
  redstone: '>=0.5.0 <0.6.0'
  redstone_mapper: '>=0.1.13 <0.2.0'
  redstone_mapper_mongo: ">=0.1.3+1 <0.2.0"
  mongo_dart: ">=0.1.47 <0.2.0"
