name: aristadart
version: 0.0.1
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: Utility classes and functions to speed development
homepage: https://github.com/redstone-dart/redstone-mvc-plugin
dependencies:
  mongo_dart: any
  redstone: any
  redstone_mapper: any
  redstone_mapper_mongo: any
  mongo_dart: any
